# Generated by Django 5.1.6 on 2025-07-25 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('blog', '0004_blogpage_is_deleted_alter_blogpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.additionaluserinfo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blogpage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.additionaluserinfo')),
            ],
            options={
                'unique_together': {('article', 'author')},
            },
        ),
    ]
