# Generated by Django 5.1.6 on 2025-07-29 01:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpage_body_alter_blogpage_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(verbose_name='Контент статьи'),
        ),
    ]
