# Generated by Django 5.1.6 on 2025-07-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
