# Generated by Django 5.1.6 on 2025-08-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articlecomment_edited_at_articlecomment_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
