# Generated by Django 5.1.6 on 2025-08-13 19:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_additionaluserinfo_syndrome_and_more'),
        ('blog', '0012_delete_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article comment', 'verbose_name_plural': 'Article comments'},
        ),
        migrations.AlterModelOptions(
            name='articlelike',
            options={'verbose_name': 'Article like', 'verbose_name_plural': 'Article likes'},
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edited at'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Soft-deleted'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='base.additionaluserinfo', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(verbose_name='Article content'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Comments count'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=250, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Soft-deleted'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes count'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Main image'),
        ),
    ]
