# Generated by Django 5.1.6 on 2025-09-18 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogpage_approved_at_blogpage_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='is_rejected',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Rejected by admin'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected at'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_articles', to=settings.AUTH_USER_MODEL, verbose_name='Rejected by'),
        ),
    ]
