# Generated by Django 5.1.6 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_blogpage_is_rejected_blogpage_rejected_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=models.CharField(max_length=500, verbose_name="Short description"),
        ),
    ]
