# Generated by Django 5.1.6 on 2026-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Hidden by author'),
        ),
    ]
