# Generated by Django 5.1.6 on 2026-07-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogpage_subscribers_notified_at_articlesubscriptionsettings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='articlesubscriptionsettings',
            new_name='blog_articl_enabled_0d609b_idx',
            old_name='blog_articl_enabled_5418df_idx',
        ),
        migrations.RenameIndex(
            model_name='articlesubscriptionsettings',
            new_name='blog_articl_site_no_52de2e_idx',
            old_name='blog_articl_site_no_20e86c_idx',
        ),
        migrations.RenameIndex(
            model_name='articlesubscriptionsettings',
            new_name='blog_articl_tg_noti_6866cf_idx',
            old_name='blog_articl_tg_noti_6f46f7_idx',
        ),
        migrations.RenameIndex(
            model_name='articlesubscriptionsettings',
            new_name='blog_articl_email_n_36e98e_idx',
            old_name='blog_articl_email__f92e2d_idx',
        ),
    ]
