# Generated by Django 5.2.3 on 2025-06-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
