# Generated by Django 5.1.6 on 2025-08-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_additionaluserinfo_friends_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow')], max_length=50),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
