# Generated by Django 5.2.3 on 2025-06-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_additionaluserinfo_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserinfo',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='additionaluserinfo',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='ready_for_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='syndrome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
