# Generated by Django 5.1.6 on 2025-08-06 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_comments', to='base.additionaluserinfo')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.medicalexam')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
