# Generated by Django 5.2.3 on 2025-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_additionaluserinfo_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
