# Generated by Django 5.1.6 on 2025-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_medicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
