# Generated by Django 5.1.6 on 2025-07-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_medicaldocument_exam_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='user_info',
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_exams', to='base.additionaluserinfo')),
            ],
            options={
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.medicalexam'),
        ),
    ]
