# Generated by Django 5.1.6 on 2025-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_examcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('EXAM_COMMENT', 'ExamComment')], max_length=50),
        ),
    ]
