# Generated by Django 5.2.3 on 2025-07-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_additionaluserinfo_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserinfo',
            name='ready_for_verification',
        ),
    ]
