# Generated by Django 5.2.3 on 2025-07-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_additionaluserinfo_ready_for_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='ready_for_verification',
            field=models.BooleanField(default=False),
        ),
    ]
