# Generated by Django 5.1.6 on 2025-08-07 15:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserinfo',
            name='syndrome',
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='syndromes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('s1', 'Синдром 1'), ('s2', 'Синдром 2'), ('s3', 'Синдром 3'), ('s4', 'Синдром 4'), ('s5', 'Синдром 5'), ('s6', 'Синдром 6')], max_length=32), blank=True, default=list, help_text='Выберите один или несколько синдромов', size=6),
        ),
    ]
