# Generated by Django 5.1.6 on 2025-08-14 01:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_additionaluserinfo_syndrome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examcomment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='syndromes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('s1', 'Syndrome 1'), ('s2', 'Syndrome 2'), ('s3', 'Syndrome 3'), ('s4', 'Syndrome 4'), ('s5', 'Syndrome 5'), ('s6', 'Syndrome 6')], max_length=32), blank=True, default=list, help_text='Select one or more syndromes', size=6),
        ),
    ]
