# Generated by Django 5.2.3 on 2025-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_additionaluserinfo_ready_for_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
