# Generated by Django 5.1.6 on 2025-08-23 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_config_alter_additionaluserinfo_syndromes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='ready_for_verification',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='examcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='exam_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('EXAM_COMMENT', 'ExamComment')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='additionaluserinfo',
            index=models.Index(fields=['user'], name='base_additi_user_id_cfb289_idx'),
        ),
        migrations.AddIndex(
            model_name='additionaluserinfo',
            index=models.Index(fields=['is_verified'], name='base_additi_is_veri_20f72f_idx'),
        ),
        migrations.AddIndex(
            model_name='additionaluserinfo',
            index=models.Index(fields=['ready_for_verification'], name='base_additi_ready_f_12e7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='examcomment',
            index=models.Index(fields=['exam', 'created_at'], name='base_examco_exam_id_8ebd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='follower',
            index=models.Index(fields=['follower', 'following', 'is_active'], name='base_follow_followe_efa410_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['exam', 'uploaded_at'], name='base_medica_exam_id_58feba_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalexam',
            index=models.Index(fields=['user_info', 'exam_date'], name='base_medica_user_in_9c96cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='base_notifi_recipie_686cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender', '-created_at'], name='base_notifi_sender__9b4330_idx'),
        ),
    ]
