# Generated by Django 5.1.6 on 2025-08-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_additionaluserinfo_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medicaldocument',
            name='base_medica_exam_id_58feba_idx',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='external_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_documents/'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
