# Generated by Django 5.1.6 on 2025-07-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='articlecomment',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='articlelike',
            old_name='created',
            new_name='created_at',
        ),
    ]
