# Generated by Django 5.1.6 on 2025-08-25 22:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_medicaldocument_base_medica_exam_id_58feba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='confirmed_syndromes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=6),
        ),
    ]
