# Generated by Django 5.1.6 on 2025-07-13 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_created_articlecomment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='user_info',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='base.additionaluserinfo',
            ),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='user_info',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='likes',
                to='base.additionaluserinfo',
            ),
        ),
        
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together={('user_info', 'article')},
        ),
        
        migrations.RemoveField(
            model_name='articlecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='articlelike',
            name='user',
        ),
    ]