# Generated by Django 5.1.6 on 2025-08-25 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_additionaluserinfo_confirmed_syndromes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('pin_code', models.CharField(max_length=8)),
                ('provider_session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_number', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('calling', 'calling'), ('verified', 'verified'), ('failed', 'failed')], db_index=True, default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='consents_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='data_processing_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='phone_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='privacy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='tos_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='additionaluserinfo',
            index=models.Index(fields=['email_verified'], name='base_additi_email_v_ee1b84_idx'),
        ),
        migrations.AddIndex(
            model_name='additionaluserinfo',
            index=models.Index(fields=['phone_verified'], name='base_additi_phone_v_dd3457_idx'),
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
