# Generated by Django 5.1.6 on 2025-07-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_articlecomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelike',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
