# Generated by Django 5.1.6 on 2025-07-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_articlelike_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='base.additionaluserinfo'),
        ),
        migrations.AlterField(
            model_name='articlelike',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to='base.additionaluserinfo'),
        ),
    ]
