# Generated by Django 5.1.6 on 2025-08-27 20:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_phoneverification_user_to_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='syndromes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=6),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('EXAM_COMMENT', 'ExamComment'), ('RECOMMENDATION', 'Recommendation')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_recommendations', to='base.additionaluserinfo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='base.additionaluserinfo')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='base_recomm_patient_1d0326_idx'), models.Index(fields=['author', '-created_at'], name='base_recomm_author__e08341_idx')],
            },
        ),
    ]
