# Generated by Django 5.1.6 on 2025-09-06 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_additionaluserinfo_syndromes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('activation_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('telegram_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to='base.additionaluserinfo')),
            ],
            options={
                'indexes': [models.Index(fields=['telegram_id'], name='base_telegr_telegra_45ddbc_idx'), models.Index(fields=['activation_token'], name='base_telegr_activat_bce888_idx'), models.Index(fields=['telegram_verified'], name='base_telegr_telegra_c6f1a7_idx')],
            },
        ),
    ]
