# Generated by Django 5.1.6 on 2025-09-15 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_telegramaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'email'), ('telegram', 'telegram')], db_index=True, max_length=16)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts_left', models.PositiveSmallIntegerField(default=5)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'channel', 'expires_at'], name='base_passwo_user_id_b39f6c_idx'), models.Index(fields=['token', 'code'], name='base_passwo_token_db0c8c_idx')],
            },
        ),
    ]
