# Generated by Django 5.1.6 on 2025-09-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_post_postcomment_postimage_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский')], default='ru', max_length=10),
        ),
    ]
