# Generated by Django 5.1.6 on 2025-09-25 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_additionaluserinfo_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='about_me',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
    ]
