# Generated by Django 5.1.6 on 2025-10-07 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_additionaluserinfo_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='about_me',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
