# Generated by Django 5.1.6 on 2025-10-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_additionaluserinfo_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden_by_reports',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Hidden by reports'),
        ),
        migrations.AddField(
            model_name='post',
            name='reports_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Reports count'),
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to='base.additionaluserinfo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='base.post')),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'author'], name='base_postre_post_id_84a3bd_idx')],
                'unique_together': {('post', 'author')},
            },
        ),
    ]
