# Generated by Django 5.1.6 on 2025-10-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_post_is_hidden_by_reports_post_reports_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='scope',
            field=models.CharField(choices=[('personal', 'Personal'), ('broadcast', 'Broadcast')], db_index=True, default='personal', max_length=16),
        ),
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], db_index=True, default='user', max_length=16),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('EXAM_COMMENT', 'ExamComment'), ('RECOMMENDATION', 'Recommendation'), ('ADMIN_MESSAGE', 'AdminMessage'), ('SYSTEM_MESSAGE', 'SystemMessage')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='base.additionaluserinfo'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['source', 'scope', '-created_at'], name='base_notifi_source_b0175f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='base_notifi_notific_8355b7_idx'),
        ),
    ]
