# Generated by Django 5.1.6 on 2025-10-13 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_helprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='is_processed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='processed'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processed at'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_help_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
