# Generated by Django 5.1.6 on 2025-10-13 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_helprequest_is_processed_helprequest_processed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('note', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_entries', to='base.additionaluserinfo')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user_info', 'date'], name='base_wellne_user_in_73a3bc_idx'), models.Index(fields=['user_info', '-created_at'], name='base_wellne_user_in_251fd1_idx')],
                'unique_together': {('user_info', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WellnessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_notifications_enabled', models.BooleanField(db_index=True, default=True)),
                ('reminder_hour', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('reminder_minute', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_settings', to='base.additionaluserinfo')),
            ],
            options={
                'indexes': [models.Index(fields=['tg_notifications_enabled'], name='base_wellne_tg_noti_0a0302_idx')],
            },
        ),
    ]
