# Generated by Django 5.1.6 on 2025-10-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_wellnessentry_wellnesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesssettings',
            name='email_notifications_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='wellnesssettings',
            index=models.Index(fields=['email_notifications_enabled'], name='base_wellne_email_n_71f6cc_idx'),
        ),
    ]
