# Generated by Django 5.1.6 on 2025-10-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_wellnesssettings_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wellnessentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='wellnessentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user_info', 'date'), name='uniq_wellness_user_date_alive'),
        ),
    ]
