# Generated by Django 5.1.6 on 2025-10-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_wellnessentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesssettings',
            name='reminder_interval',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Never'), (1, 'Every day'), (3, 'Every 3 days'), (7, 'Every 7 days')], db_index=True, default=3),
        ),
        migrations.AddIndex(
            model_name='wellnesssettings',
            index=models.Index(fields=['reminder_interval'], name='base_wellne_reminde_e8ebee_idx'),
        ),
    ]
