# Generated by Django 5.1.6 on 2025-10-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_wellnesssettings_reminder_interval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaluserinfo',
            options={'permissions': [('view_patient_list', 'Can view patient list')]},
        ),
        migrations.AlterModelOptions(
            name='examcomment',
            options={'ordering': ['created_at'], 'permissions': [('comment_exams', 'Can comment exams'), ('moderate_exam_comments', 'Can moderate exam comments')]},
        ),
        migrations.AlterModelOptions(
            name='helprequest',
            options={'ordering': ['-created_at'], 'permissions': [('view_help_requests', 'Can view help requests'), ('process_help_requests', 'Can process help requests')], 'verbose_name': 'help request', 'verbose_name_plural': 'help requests'},
        ),
        migrations.AlterModelOptions(
            name='medicalexam',
            options={'ordering': ['-exam_date', '-created_at'], 'permissions': [('view_patient_exams', 'Can view patient exams'), ('modify_patient_exams', 'Can create and edit patient exams')]},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at'], 'permissions': [('view_recommendations', 'Can view recommendations'), ('write_recommendations', 'Can write recommendations')]},
        ),
    ]
