# Generated by Django 5.1.6 on 2025-10-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_create_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': [('send_notifications', 'Can send notifications')]},
        ),
    ]
