# Generated by Django 5.1.6 on 2025-10-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='telegram'),
        ),
    ]
