# Generated by Django 5.1.6 on 2025-10-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_helprequest_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='censorship_enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pre-moderation enabled'),
        ),
    ]
