# Generated by Django 5.1.6 on 2025-10-21 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_additionaluserinfo_censorship_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Banned at'),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL, verbose_name='Banned by'),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='banned_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ban reason'),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Banned'),
        ),
        migrations.AddIndex(
            model_name='additionaluserinfo',
            index=models.Index(fields=['is_banned'], name='base_additi_is_bann_5741fb_idx'),
        ),
    ]
