# Generated by Django 5.1.6 on 2026-01-05 12:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_wellnesssettings_reminder_tz'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(help_text='Example: Pregabalin 75 mg daily', max_length=255, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name='Medication description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='base.additionaluserinfo', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_info', 'is_deleted'], name='base_medica_user_in_d3dd7b_idx'), models.Index(fields=['user_info', '-created_at'], name='base_medica_user_in_bca65c_idx')],
            },
        ),
    ]
