# Generated by Django 5.1.6 on 2026-01-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_help_request_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER INDEX IF EXISTS base_patien_patient_7c58ab_idx "
                    "RENAME TO base_patien_patient_eb1618_idx;"
                ),
                migrations.RunSQL(
                    "ALTER INDEX IF EXISTS base_patien_doctor_86db2f_idx "
                    "RENAME TO base_patien_doctor__399a38_idx;"
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='patientaccessrequest',
                    new_name='base_patien_patient_eb1618_idx',
                    old_name='base_patien_patient_7c58ab_idx',
                ),
                migrations.RenameIndex(
                    model_name='patientaccessrequest',
                    new_name='base_patien_doctor__399a38_idx',
                    old_name='base_patien_doctor_86db2f_idx',
                ),
            ],
        ),
    ]
