# Generated by Django 5.1.6 on 2026-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_additionaluserinfo_show_syndromes_in_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('EXAM_COMMENT', 'ExamComment'), ('RECOMMENDATION', 'Recommendation'), ('ADMIN_MESSAGE', 'AdminMessage'), ('SYSTEM_MESSAGE', 'SystemMessage'), ('ACCESS_REQUEST', 'AccessRequest'), ('ACCESS_GRANTED', 'AccessGranted'), ('ACCESS_DENIED', 'AccessDenied'), ('ARTICLE_PUBLISHED', 'ArticlePublished')], db_index=True, max_length=50),
        ),
    ]
